#!/bin/sh
### BEGIN INIT INFO
# Provides:          driveapi
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       drive api
### END INIT INFO

SCRIPT=~/pi/rover/api/api.py
RUNAS=root

PIDFILE=/var/run/driveapi.pid
LOGFILE=/var/log/driveapi.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="python $SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  pkill -TERM -P $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

install() {
  echo -n "Are you sure you wan to install this service? [yes|no] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    echo installing Drive Control UI Service
    cp -u services/driveapi /etc/init.d/driveapi
    chmod +x /etc/init.d/driveapi
    chown root:root /etc/init.d/driveapi
  fi
}

uninstall() {
  echo -n "Are you sure you want to uninstall this service? [yes|no] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f driveapi remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  install)
    install
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
